/*
* generated by Xtext
*/
package com.knitml.dsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import com.knitml.dsl.services.KnittingExpressionLanguageGrammarAccess;

public class KnittingExpressionLanguageParser extends AbstractContentAssistParser {
	
	@Inject
	private KnittingExpressionLanguageGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected com.knitml.dsl.ui.contentassist.antlr.internal.InternalKnittingExpressionLanguageParser createParser() {
		com.knitml.dsl.ui.contentassist.antlr.internal.InternalKnittingExpressionLanguageParser result = new com.knitml.dsl.ui.contentassist.antlr.internal.InternalKnittingExpressionLanguageParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getBlockOperationAccess().getAlternatives(), "rule__BlockOperation__Alternatives");
					put(grammarAccess.getInstructionAccess().getShapeAlternatives_3_2_1_0(), "rule__Instruction__ShapeAlternatives_3_2_1_0");
					put(grammarAccess.getInstructionAccess().getAlternatives_3_3_2(), "rule__Instruction__Alternatives_3_3_2");
					put(grammarAccess.getInstructionAccess().getAlternatives_4(), "rule__Instruction__Alternatives_4");
					put(grammarAccess.getRowAccess().getLabelAlternatives_2_0(), "rule__Row__LabelAlternatives_2_0");
					put(grammarAccess.getRowAccess().getAlternatives_3(), "rule__Row__Alternatives_3");
					put(grammarAccess.getRowAccess().getSubsequentAlternatives_3_1_2_2_0(), "rule__Row__SubsequentAlternatives_3_1_2_2_0");
					put(grammarAccess.getRowAccess().getAlternatives_3_1_2_3(), "rule__Row__Alternatives_3_1_2_3");
					put(grammarAccess.getRowAccess().getSideAlternatives_4_0_0(), "rule__Row__SideAlternatives_4_0_0");
					put(grammarAccess.getRepeatInstructionAccess().getAlternatives_0(), "rule__RepeatInstruction__Alternatives_0");
					put(grammarAccess.getRepeatInstructionAccess().getAlternatives_2(), "rule__RepeatInstruction__Alternatives_2");
					put(grammarAccess.getRepeatInstructionAccess().getAlternatives_2_1_2(), "rule__RepeatInstruction__Alternatives_2_1_2");
					put(grammarAccess.getRepeatInstructionAccess().getAlternatives_2_2_0(), "rule__RepeatInstruction__Alternatives_2_2_0");
					put(grammarAccess.getRepeatInstructionAccess().getAlternatives_2_2_1(), "rule__RepeatInstruction__Alternatives_2_2_1");
					put(grammarAccess.getRepeatInstructionAccess().getAdditionalTimesAlternatives_2_3_1_0(), "rule__RepeatInstruction__AdditionalTimesAlternatives_2_3_1_0");
					put(grammarAccess.getInlineOperationAccess().getAlternatives(), "rule__InlineOperation__Alternatives");
					put(grammarAccess.getKnitAccess().getAlternatives_0(), "rule__Knit__Alternatives_0");
					put(grammarAccess.getKnitAccess().getThroughTrailingLoopAlternatives_4_1_0(), "rule__Knit__ThroughTrailingLoopAlternatives_4_1_0");
					put(grammarAccess.getPurlAccess().getAlternatives_0(), "rule__Purl__Alternatives_0");
					put(grammarAccess.getPurlAccess().getThroughTrailingLoopAlternatives_4_1_0(), "rule__Purl__ThroughTrailingLoopAlternatives_4_1_0");
					put(grammarAccess.getSlipAccess().getReverseAlternatives_1_0(), "rule__Slip__ReverseAlternatives_1_0");
					put(grammarAccess.getSlipAccess().getAlternatives_2(), "rule__Slip__Alternatives_2");
					put(grammarAccess.getSlipAccess().getAlternatives_3(), "rule__Slip__Alternatives_3");
					put(grammarAccess.getSlipAccess().getYarnPositionAlternatives_5_0(), "rule__Slip__YarnPositionAlternatives_5_0");
					put(grammarAccess.getRepeatAccess().getAlternatives(), "rule__Repeat__Alternatives");
					put(grammarAccess.getRepeatAccess().getAlternatives_0_0(), "rule__Repeat__Alternatives_0_0");
					put(grammarAccess.getRepeatAccess().getAlternatives_1_4_1(), "rule__Repeat__Alternatives_1_4_1");
					put(grammarAccess.getBindOffAccess().getAlternatives_0(), "rule__BindOff__Alternatives_0");
					put(grammarAccess.getBindOffAccess().getAlternatives_1(), "rule__BindOff__Alternatives_1");
					put(grammarAccess.getRepeatSpecAccess().getAlternatives(), "rule__RepeatSpec__Alternatives");
					put(grammarAccess.getStitchLiteralAccess().getAlternatives(), "rule__StitchLiteral__Alternatives");
					put(grammarAccess.getUnitOfMeasureAccess().getAlternatives(), "rule__UnitOfMeasure__Alternatives");
					put(grammarAccess.getWiseAccess().getAlternatives(), "rule__Wise__Alternatives");
					put(grammarAccess.getPatternAccess().getGroup(), "rule__Pattern__Group__0");
					put(grammarAccess.getPatternAccess().getGroup_2(), "rule__Pattern__Group_2__0");
					put(grammarAccess.getInstructionAccess().getGroup(), "rule__Instruction__Group__0");
					put(grammarAccess.getInstructionAccess().getGroup_3(), "rule__Instruction__Group_3__0");
					put(grammarAccess.getInstructionAccess().getGroup_3_2(), "rule__Instruction__Group_3_2__0");
					put(grammarAccess.getInstructionAccess().getGroup_3_3(), "rule__Instruction__Group_3_3__0");
					put(grammarAccess.getInstructionAccess().getGroup_4_0(), "rule__Instruction__Group_4_0__0");
					put(grammarAccess.getInstructionAccess().getGroup_4_0_3(), "rule__Instruction__Group_4_0_3__0");
					put(grammarAccess.getInstructionAccess().getGroup_4_1(), "rule__Instruction__Group_4_1__0");
					put(grammarAccess.getRowAccess().getGroup(), "rule__Row__Group__0");
					put(grammarAccess.getRowAccess().getGroup_3_1(), "rule__Row__Group_3_1__0");
					put(grammarAccess.getRowAccess().getGroup_3_1_1(), "rule__Row__Group_3_1_1__0");
					put(grammarAccess.getRowAccess().getGroup_3_1_2(), "rule__Row__Group_3_1_2__0");
					put(grammarAccess.getRowAccess().getGroup_4_1(), "rule__Row__Group_4_1__0");
					put(grammarAccess.getRowAccess().getGroup_5(), "rule__Row__Group_5__0");
					put(grammarAccess.getRowAccess().getGroup_5_1(), "rule__Row__Group_5_1__0");
					put(grammarAccess.getRowAccess().getGroup_5_2(), "rule__Row__Group_5_2__0");
					put(grammarAccess.getRowAccess().getGroup_9(), "rule__Row__Group_9__0");
					put(grammarAccess.getRepeatInstructionAccess().getGroup(), "rule__RepeatInstruction__Group__0");
					put(grammarAccess.getRepeatInstructionAccess().getGroup_2_0(), "rule__RepeatInstruction__Group_2_0__0");
					put(grammarAccess.getRepeatInstructionAccess().getGroup_2_1(), "rule__RepeatInstruction__Group_2_1__0");
					put(grammarAccess.getRepeatInstructionAccess().getGroup_2_2(), "rule__RepeatInstruction__Group_2_2__0");
					put(grammarAccess.getRepeatInstructionAccess().getGroup_2_2_0_1(), "rule__RepeatInstruction__Group_2_2_0_1__0");
					put(grammarAccess.getRepeatInstructionAccess().getGroup_2_3(), "rule__RepeatInstruction__Group_2_3__0");
					put(grammarAccess.getMessageAccess().getGroup(), "rule__Message__Group__0");
					put(grammarAccess.getMessageAccess().getGroup_1(), "rule__Message__Group_1__0");
					put(grammarAccess.getKnitAccess().getGroup(), "rule__Knit__Group__0");
					put(grammarAccess.getKnitAccess().getGroup_5(), "rule__Knit__Group_5__0");
					put(grammarAccess.getKnitAccess().getGroup_6(), "rule__Knit__Group_6__0");
					put(grammarAccess.getPurlAccess().getGroup(), "rule__Purl__Group__0");
					put(grammarAccess.getPurlAccess().getGroup_5(), "rule__Purl__Group_5__0");
					put(grammarAccess.getPurlAccess().getGroup_6(), "rule__Purl__Group_6__0");
					put(grammarAccess.getSlipAccess().getGroup(), "rule__Slip__Group__0");
					put(grammarAccess.getSlipAccess().getGroup_3_0(), "rule__Slip__Group_3_0__0");
					put(grammarAccess.getRepeatAccess().getGroup_0(), "rule__Repeat__Group_0__0");
					put(grammarAccess.getRepeatAccess().getGroup_0_3(), "rule__Repeat__Group_0_3__0");
					put(grammarAccess.getRepeatAccess().getGroup_1(), "rule__Repeat__Group_1__0");
					put(grammarAccess.getRepeatAccess().getGroup_1_2(), "rule__Repeat__Group_1_2__0");
					put(grammarAccess.getRepeatAccess().getGroup_1_4(), "rule__Repeat__Group_1_4__0");
					put(grammarAccess.getBindOffAccess().getGroup(), "rule__BindOff__Group__0");
					put(grammarAccess.getBindOffAccess().getGroup_4(), "rule__BindOff__Group_4__0");
					put(grammarAccess.getRepeatSpecAccess().getGroup_2(), "rule__RepeatSpec__Group_2__0");
					put(grammarAccess.getRepeatSpecAccess().getGroup_3(), "rule__RepeatSpec__Group_3__0");
					put(grammarAccess.getRepeatSpecAccess().getGroup_4(), "rule__RepeatSpec__Group_4__0");
					put(grammarAccess.getRepeatSpecAccess().getGroup_5(), "rule__RepeatSpec__Group_5__0");
					put(grammarAccess.getWithKeyAccess().getGroup(), "rule__WithKey__Group__0");
					put(grammarAccess.getRangeAccess().getGroup(), "rule__Range__Group__0");
					put(grammarAccess.getPatternAccess().getElementsAssignment_1(), "rule__Pattern__ElementsAssignment_1");
					put(grammarAccess.getPatternAccess().getElementsAssignment_2_1(), "rule__Pattern__ElementsAssignment_2_1");
					put(grammarAccess.getInstructionAccess().getNameAssignment_1(), "rule__Instruction__NameAssignment_1");
					put(grammarAccess.getInstructionAccess().getLabelAssignment_2(), "rule__Instruction__LabelAssignment_2");
					put(grammarAccess.getInstructionAccess().getWithKeyAssignment_3_1(), "rule__Instruction__WithKeyAssignment_3_1");
					put(grammarAccess.getInstructionAccess().getShapeAssignment_3_2_1(), "rule__Instruction__ShapeAssignment_3_2_1");
					put(grammarAccess.getInstructionAccess().getRowCountAssignment_3_3_1(), "rule__Instruction__RowCountAssignment_3_3_1");
					put(grammarAccess.getInstructionAccess().getRowsAssignment_4_0_2(), "rule__Instruction__RowsAssignment_4_0_2");
					put(grammarAccess.getInstructionAccess().getRowsAssignment_4_0_3_1(), "rule__Instruction__RowsAssignment_4_0_3_1");
					put(grammarAccess.getInstructionAccess().getRowsAssignment_4_1_2(), "rule__Instruction__RowsAssignment_4_1_2");
					put(grammarAccess.getRowAccess().getNextRowAssignment_0(), "rule__Row__NextRowAssignment_0");
					put(grammarAccess.getRowAccess().getShortRowAssignment_1_0(), "rule__Row__ShortRowAssignment_1_0");
					put(grammarAccess.getRowAccess().getLongRowAssignment_1_1(), "rule__Row__LongRowAssignment_1_1");
					put(grammarAccess.getRowAccess().getLabelAssignment_2(), "rule__Row__LabelAssignment_2");
					put(grammarAccess.getRowAccess().getRangeAssignment_3_0(), "rule__Row__RangeAssignment_3_0");
					put(grammarAccess.getRowAccess().getNumberAssignment_3_1_0(), "rule__Row__NumberAssignment_3_1_0");
					put(grammarAccess.getRowAccess().getNumberAssignment_3_1_1_1(), "rule__Row__NumberAssignment_3_1_1_1");
					put(grammarAccess.getRowAccess().getSubsequentAssignment_3_1_2_2(), "rule__Row__SubsequentAssignment_3_1_2_2");
					put(grammarAccess.getRowAccess().getSideAssignment_4_0(), "rule__Row__SideAssignment_4_0");
					put(grammarAccess.getRowAccess().getYarnRefAssignment_4_1_1(), "rule__Row__YarnRefAssignment_4_1_1");
					put(grammarAccess.getRowAccess().getInformAssignment_5_1_1(), "rule__Row__InformAssignment_5_1_1");
					put(grammarAccess.getRowAccess().getResetAssignment_5_2_1(), "rule__Row__ResetAssignment_5_2_1");
					put(grammarAccess.getRowAccess().getOperationsAssignment_8(), "rule__Row__OperationsAssignment_8");
					put(grammarAccess.getRowAccess().getOperationsAssignment_9_1(), "rule__Row__OperationsAssignment_9_1");
					put(grammarAccess.getRepeatInstructionAccess().getInstructionAssignment_1(), "rule__RepeatInstruction__InstructionAssignment_1");
					put(grammarAccess.getRepeatInstructionAccess().getDesiredLengthAssignment_2_0_1(), "rule__RepeatInstruction__DesiredLengthAssignment_2_0_1");
					put(grammarAccess.getRepeatInstructionAccess().getValueAssignment_2_1_1(), "rule__RepeatInstruction__ValueAssignment_2_1_1");
					put(grammarAccess.getRepeatInstructionAccess().getRemainAssignment_2_1_3(), "rule__RepeatInstruction__RemainAssignment_2_1_3");
					put(grammarAccess.getRepeatInstructionAccess().getValueAssignment_2_2_1_0(), "rule__RepeatInstruction__ValueAssignment_2_2_1_0");
					put(grammarAccess.getRepeatInstructionAccess().getDecimalValueAssignment_2_2_1_1(), "rule__RepeatInstruction__DecimalValueAssignment_2_2_1_1");
					put(grammarAccess.getRepeatInstructionAccess().getUnitAssignment_2_2_2(), "rule__RepeatInstruction__UnitAssignment_2_2_2");
					put(grammarAccess.getRepeatInstructionAccess().getValueAssignment_2_3_0(), "rule__RepeatInstruction__ValueAssignment_2_3_0");
					put(grammarAccess.getRepeatInstructionAccess().getAdditionalTimesAssignment_2_3_1(), "rule__RepeatInstruction__AdditionalTimesAssignment_2_3_1");
					put(grammarAccess.getMessageAccess().getMessageAssignment_0(), "rule__Message__MessageAssignment_0");
					put(grammarAccess.getMessageAccess().getWithKeyAssignment_1_1(), "rule__Message__WithKeyAssignment_1_1");
					put(grammarAccess.getKnitAccess().getNumberAssignment_2(), "rule__Knit__NumberAssignment_2");
					put(grammarAccess.getKnitAccess().getTogetherAssignment_4_0(), "rule__Knit__TogetherAssignment_4_0");
					put(grammarAccess.getKnitAccess().getThroughTrailingLoopAssignment_4_1(), "rule__Knit__ThroughTrailingLoopAssignment_4_1");
					put(grammarAccess.getKnitAccess().getYarnRefAssignment_5_1(), "rule__Knit__YarnRefAssignment_5_1");
					put(grammarAccess.getKnitAccess().getRepeatAssignment_6_1(), "rule__Knit__RepeatAssignment_6_1");
					put(grammarAccess.getPurlAccess().getNumberAssignment_2(), "rule__Purl__NumberAssignment_2");
					put(grammarAccess.getPurlAccess().getTogetherAssignment_4_0(), "rule__Purl__TogetherAssignment_4_0");
					put(grammarAccess.getPurlAccess().getThroughTrailingLoopAssignment_4_1(), "rule__Purl__ThroughTrailingLoopAssignment_4_1");
					put(grammarAccess.getPurlAccess().getYarnRefAssignment_5_1(), "rule__Purl__YarnRefAssignment_5_1");
					put(grammarAccess.getPurlAccess().getRepeatAssignment_6_1(), "rule__Purl__RepeatAssignment_6_1");
					put(grammarAccess.getSlipAccess().getReverseAssignment_1(), "rule__Slip__ReverseAssignment_1");
					put(grammarAccess.getSlipAccess().getNumberAssignment_3_0_0(), "rule__Slip__NumberAssignment_3_0_0");
					put(grammarAccess.getSlipAccess().getWiseAssignment_4(), "rule__Slip__WiseAssignment_4");
					put(grammarAccess.getSlipAccess().getYarnPositionAssignment_5(), "rule__Slip__YarnPositionAssignment_5");
					put(grammarAccess.getRepeatAccess().getOperationsAssignment_0_2(), "rule__Repeat__OperationsAssignment_0_2");
					put(grammarAccess.getRepeatAccess().getOperationsAssignment_0_3_1(), "rule__Repeat__OperationsAssignment_0_3_1");
					put(grammarAccess.getRepeatAccess().getSpecAssignment_0_6(), "rule__Repeat__SpecAssignment_0_6");
					put(grammarAccess.getRepeatAccess().getOperationsAssignment_1_1(), "rule__Repeat__OperationsAssignment_1_1");
					put(grammarAccess.getRepeatAccess().getOperationsAssignment_1_2_1(), "rule__Repeat__OperationsAssignment_1_2_1");
					put(grammarAccess.getRepeatAccess().getSpecAssignment_1_6(), "rule__Repeat__SpecAssignment_1_6");
					put(grammarAccess.getBindOffAccess().getAllAssignment_1_0(), "rule__BindOff__AllAssignment_1_0");
					put(grammarAccess.getBindOffAccess().getValueAssignment_1_1(), "rule__BindOff__ValueAssignment_1_1");
					put(grammarAccess.getBindOffAccess().getWiseAssignment_3(), "rule__BindOff__WiseAssignment_3");
					put(grammarAccess.getBindOffAccess().getYarnRefAssignment_4_1(), "rule__BindOff__YarnRefAssignment_4_1");
					put(grammarAccess.getRepeatSpecAccess().getToEndAssignment_0(), "rule__RepeatSpec__ToEndAssignment_0");
					put(grammarAccess.getRepeatSpecAccess().getToMarkerAssignment_1(), "rule__RepeatSpec__ToMarkerAssignment_1");
					put(grammarAccess.getRepeatSpecAccess().getValueAssignment_2_0(), "rule__RepeatSpec__ValueAssignment_2_0");
					put(grammarAccess.getRepeatSpecAccess().getBeforeEndAssignment_2_2(), "rule__RepeatSpec__BeforeEndAssignment_2_2");
					put(grammarAccess.getRepeatSpecAccess().getValueAssignment_3_0(), "rule__RepeatSpec__ValueAssignment_3_0");
					put(grammarAccess.getRepeatSpecAccess().getBeforeGapAssignment_3_2(), "rule__RepeatSpec__BeforeGapAssignment_3_2");
					put(grammarAccess.getRepeatSpecAccess().getValueAssignment_4_0(), "rule__RepeatSpec__ValueAssignment_4_0");
					put(grammarAccess.getRepeatSpecAccess().getBeforeMarkerAssignment_4_2(), "rule__RepeatSpec__BeforeMarkerAssignment_4_2");
					put(grammarAccess.getRepeatSpecAccess().getValueAssignment_5_0(), "rule__RepeatSpec__ValueAssignment_5_0");
					put(grammarAccess.getRepeatSpecAccess().getTimesAssignment_5_1(), "rule__RepeatSpec__TimesAssignment_5_1");
					put(grammarAccess.getWithKeyAccess().getMessageKeyAssignment_3(), "rule__WithKey__MessageKeyAssignment_3");
					put(grammarAccess.getRangeAccess().getMinAssignment_0(), "rule__Range__MinAssignment_0");
					put(grammarAccess.getRangeAccess().getMaxAssignment_2(), "rule__Range__MaxAssignment_2");
					put(grammarAccess.getRowAccess().getUnorderedGroup_1(), "rule__Row__UnorderedGroup_1");
					put(grammarAccess.getRowAccess().getUnorderedGroup_4(), "rule__Row__UnorderedGroup_4");
					put(grammarAccess.getKnitAccess().getUnorderedGroup_4(), "rule__Knit__UnorderedGroup_4");
					put(grammarAccess.getPurlAccess().getUnorderedGroup_4(), "rule__Purl__UnorderedGroup_4");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			com.knitml.dsl.ui.contentassist.antlr.internal.InternalKnittingExpressionLanguageParser typedParser = (com.knitml.dsl.ui.contentassist.antlr.internal.InternalKnittingExpressionLanguageParser) parser;
			typedParser.entryRulePattern();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public KnittingExpressionLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(KnittingExpressionLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
