/*
 * generated by Xtext
 */
package com.knitml.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class KnittingExpressionLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return com.knitml.dsl.ui.internal.KnittingExpressionLanguageActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return com.knitml.dsl.ui.internal.KnittingExpressionLanguageActivator.getInstance().getInjector("com.knitml.dsl.KnittingExpressionLanguage");
	}
	
}
