/*
* generated by Xtext
*/
package com.knitml.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class KnittingExpressionLanguageUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.knitml.dsl.ui.internal.KnittingExpressionLanguageActivator.getInstance().getInjector("com.knitml.dsl.KnittingExpressionLanguage");
	}
	
}
