/*
* generated by Xtext
*/
package com.knitml.dsl.ui.contentassist;

import com.knitml.dsl.ui.contentassist.AbstractKnittingExpressionLanguageProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class KnittingExpressionLanguageProposalProvider extends AbstractKnittingExpressionLanguageProposalProvider {

}
