/*
* generated by Xtext
*/
package com.knitml.dsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class KnittingExpressionLanguageOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
