/*
* generated by Xtext
*/
package com.knitml.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class KnittingExpressionLanguageAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/knitml/dsl/parser/antlr/internal/InternalKnittingExpressionLanguage.tokens");
	}
}
